version: 2

sources:
  - name: raw
    database: ECOMMERCE_DB
    schema: RAW
    tables:
      - name: orders
        columns:
          - name: order_id
            tests: [not_null]
      - name: order_items
        columns:
          - name: order_id
            tests: [not_null]
      - name: order_payments
      - name: customers
      - name: products
      - name: sellers
      - name: product_category_translation
