name: 'ecommerce_dbt'
version: '1.0.0'
profile: 'ecommerce_dbt'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:

    staging:
      +schema: STAGING
      +materialized: view

    marts:
      +schema: MART
      +materialized: table
